# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: java:7
pipelines:
  tags:                         
    '*':                 
      - step:                   
          script:
          - bash ./gradlew assemble